FeatureScript 2931;
import(path : "onshape/std/common.fs", version : "2931.0");

// THE ENGINE — Full Robot Blueprint
// Generated by The Blueprint B.7 — CAD Builder
// Frame: 27.0" x 27.0"
// Mechanisms: intake, conveyor, flywheel, climber

annotation { "Feature Type Name" : "2950 Blueprint Robot" }
export const blueprintRobot = defineFeature(function(context is Context, id is Id, definition is map)
    precondition {}
    {
        // front_rail
        fCuboid(context, id + "front_rail", {
            "corner1" : vector(0.0, 0.0, 0.0) * millimeter,
            "corner2" : vector(685.8, 50.8, 25.4) * millimeter
        });
        // back_rail
        fCuboid(context, id + "back_rail", {
            "corner1" : vector(0.0, 635.0, 0.0) * millimeter,
            "corner2" : vector(685.8, 685.8, 25.4) * millimeter
        });
        // left_rail
        fCuboid(context, id + "left_rail", {
            "corner1" : vector(0.0, 50.8, 0.0) * millimeter,
            "corner2" : vector(50.8, 635.0, 25.4) * millimeter
        });
        // right_rail
        fCuboid(context, id + "right_rail", {
            "corner1" : vector(635.0, 50.8, 0.0) * millimeter,
            "corner2" : vector(685.8, 635.0, 25.4) * millimeter
        });
        // cross_0
        fCuboid(context, id + "cross_0", {
            "corner1" : vector(50.8, 609.6, 0.0) * millimeter,
            "corner2" : vector(635.0, 635.0, 25.4) * millimeter
        });
        // cross_1
        fCuboid(context, id + "cross_1", {
            "corner1" : vector(50.8, 50.8, 0.0) * millimeter,
            "corner2" : vector(635.0, 76.2, 25.4) * millimeter
        });
        // cross_2
        fCuboid(context, id + "cross_2", {
            "corner1" : vector(50.8, 330.2, 0.0) * millimeter,
            "corner2" : vector(635.0, 355.6, 25.4) * millimeter
        });
        // bellypan
        fCuboid(context, id + "bellypan", {
            "corner1" : vector(1.0, 1.0, -3.2) * millimeter,
            "corner2" : vector(684.8, 684.8, 0.0) * millimeter
        });
        // mod_body_0
        fCuboid(context, id + "mod_body_0", {
            "corner1" : vector(25.4, 25.4, 25.4) * millimeter,
            "corner2" : vector(101.6, 101.6, 101.6) * millimeter
        });
        // mod_wheel_0
        fCuboid(context, id + "mod_wheel_0", {
            "corner1" : vector(44.5, 22.2, -85.7) * millimeter,
            "corner2" : vector(82.5, 104.8, -3.2) * millimeter
        });
        // mod_body_1
        fCuboid(context, id + "mod_body_1", {
            "corner1" : vector(584.2, 25.4, 25.4) * millimeter,
            "corner2" : vector(660.4, 101.6, 101.6) * millimeter
        });
        // mod_wheel_1
        fCuboid(context, id + "mod_wheel_1", {
            "corner1" : vector(603.2, 22.2, -85.7) * millimeter,
            "corner2" : vector(641.3, 104.8, -3.2) * millimeter
        });
        // mod_body_2
        fCuboid(context, id + "mod_body_2", {
            "corner1" : vector(25.4, 584.2, 25.4) * millimeter,
            "corner2" : vector(101.6, 660.4, 101.6) * millimeter
        });
        // mod_wheel_2
        fCuboid(context, id + "mod_wheel_2", {
            "corner1" : vector(44.5, 581.0, -85.7) * millimeter,
            "corner2" : vector(82.5, 663.6, -3.2) * millimeter
        });
        // mod_body_3
        fCuboid(context, id + "mod_body_3", {
            "corner1" : vector(584.2, 584.2, 25.4) * millimeter,
            "corner2" : vector(660.4, 660.4, 101.6) * millimeter
        });
        // mod_wheel_3
        fCuboid(context, id + "mod_wheel_3", {
            "corner1" : vector(603.2, 581.0, -85.7) * millimeter,
            "corner2" : vector(641.3, 663.6, -3.2) * millimeter
        });
        // intake_plate_L
        fCuboid(context, id + "intake_plate_L", {
            "corner1" : vector(25.4, 254.0, 25.4) * millimeter,
            "corner2" : vector(31.7, 596.9, 317.5) * millimeter
        });
        // intake_plate_R
        fCuboid(context, id + "intake_plate_R", {
            "corner1" : vector(654.0, 254.0, 25.4) * millimeter,
            "corner2" : vector(660.4, 596.9, 317.5) * millimeter
        });
        // intake_roller_bottom
        fCuboid(context, id + "intake_roller_bottom", {
            "corner1" : vector(31.7, 495.3, 25.4) * millimeter,
            "corner2" : vector(654.0, 596.9, 127.0) * millimeter
        });
        // intake_roller_top
        fCuboid(context, id + "intake_roller_top", {
            "corner1" : vector(31.7, 495.3, 215.9) * millimeter,
            "corner2" : vector(654.0, 596.9, 317.5) * millimeter
        });
        // intake_back_plate
        fCuboid(context, id + "intake_back_plate", {
            "corner1" : vector(25.4, 254.0, 25.4) * millimeter,
            "corner2" : vector(660.4, 260.4, 317.5) * millimeter
        });
        // intake_pivot_shaft
        fCuboid(context, id + "intake_pivot_shaft", {
            "corner1" : vector(25.4, 254.0, 25.4) * millimeter,
            "corner2" : vector(660.4, 266.7, 38.1) * millimeter
        });
        // conveyor_rail_L
        fCuboid(context, id + "conveyor_rail_L", {
            "corner1" : vector(190.5, 38.1, 25.4) * millimeter,
            "corner2" : vector(215.9, 647.7, 317.5) * millimeter
        });
        // conveyor_rail_R
        fCuboid(context, id + "conveyor_rail_R", {
            "corner1" : vector(469.9, 38.1, 25.4) * millimeter,
            "corner2" : vector(495.3, 647.7, 317.5) * millimeter
        });
        // conveyor_belt
        fCuboid(context, id + "conveyor_belt", {
            "corner1" : vector(215.9, 38.1, 168.3) * millimeter,
            "corner2" : vector(469.9, 647.7, 174.6) * millimeter
        });
        // conveyor_roller_front
        fCuboid(context, id + "conveyor_roller_front", {
            "corner1" : vector(215.9, 596.9, 146.1) * millimeter,
            "corner2" : vector(469.9, 647.7, 196.9) * millimeter
        });
        // conveyor_roller_back
        fCuboid(context, id + "conveyor_roller_back", {
            "corner1" : vector(215.9, 38.1, 146.1) * millimeter,
            "corner2" : vector(469.9, 88.9, 196.9) * millimeter
        });
        // flywheel_plate_L
        fCuboid(context, id + "flywheel_plate_L", {
            "corner1" : vector(215.9, 69.8, 317.5) * millimeter,
            "corner2" : vector(222.2, 273.0, 520.7) * millimeter
        });
        // flywheel_plate_R
        fCuboid(context, id + "flywheel_plate_R", {
            "corner1" : vector(463.5, 69.8, 317.5) * millimeter,
            "corner2" : vector(469.9, 273.0, 520.7) * millimeter
        });
        // flywheel_wheel_1
        fCuboid(context, id + "flywheel_wheel_1", {
            "corner1" : vector(323.8, 95.2, 317.5) * millimeter,
            "corner2" : vector(361.9, 247.6, 469.9) * millimeter
        });
        // flywheel_wheel_2
        fCuboid(context, id + "flywheel_wheel_2", {
            "corner1" : vector(323.8, 95.2, 368.3) * millimeter,
            "corner2" : vector(361.9, 247.6, 520.7) * millimeter
        });
        // flywheel_hood
        fCuboid(context, id + "flywheel_hood", {
            "corner1" : vector(222.2, 247.6, 317.5) * millimeter,
            "corner2" : vector(463.5, 254.0, 520.7) * millimeter
        });
        // flywheel_back
        fCuboid(context, id + "flywheel_back", {
            "corner1" : vector(222.2, 69.8, 317.5) * millimeter,
            "corner2" : vector(463.5, 76.2, 520.7) * millimeter
        });
        // climber_outer_tube
        fCuboid(context, id + "climber_outer_tube", {
            "corner1" : vector(323.8, 82.5, 25.4) * millimeter,
            "corner2" : vector(361.9, 120.6, 635.0) * millimeter
        });
        // climber_inner_tube
        fCuboid(context, id + "climber_inner_tube", {
            "corner1" : vector(330.2, 88.9, 101.6) * millimeter,
            "corner2" : vector(355.6, 114.3, 1651.0) * millimeter
        });
        // climber_base
        fCuboid(context, id + "climber_base", {
            "corner1" : vector(304.8, 63.5, 25.4) * millimeter,
            "corner2" : vector(381.0, 139.7, 101.6) * millimeter
        });
        // climber_hook
        fCuboid(context, id + "climber_hook", {
            "corner1" : vector(317.5, 88.9, 1651.0) * millimeter,
            "corner2" : vector(368.3, 114.3, 1676.4) * millimeter
        });
        // elec_battery
        fCuboid(context, id + "elec_battery", {
            "corner1" : vector(252.4, 254.1, 0.0) * millimeter,
            "corner2" : vector(433.4, 330.1, 167.0) * millimeter
        });
        // elec_pdh
        fCuboid(context, id + "elec_pdh", {
            "corner1" : vector(266.7, 120.6, 0.0) * millimeter,
            "corner2" : vector(419.1, 222.2, 38.1) * millimeter
        });
        // elec_roborio
        fCuboid(context, id + "elec_roborio", {
            "corner1" : vector(254.0, 412.8, 0.0) * millimeter,
            "corner2" : vector(431.8, 501.6, 38.1) * millimeter
        });
        // elec_radio
        fCuboid(context, id + "elec_radio", {
            "corner1" : vector(275.4, 456.8, 0.0) * millimeter,
            "corner2" : vector(410.4, 571.8, 30.0) * millimeter
        });
        // elec_main_breaker
        fCuboid(context, id + "elec_main_breaker", {
            "corner1" : vector(485.8, 314.4, 0.0) * millimeter,
            "corner2" : vector(542.8, 371.4, 38.0) * millimeter
        });
    });
