FeatureScript 2931;
import(path : "onshape/std/common.fs", version : "2931.0");

// THE ENGINE — Real Tube Frame Robot Blueprint
// Generated by The Blueprint — CAD Builder (Evolution P1)
// Frame: 27.0" x 27.0"
// Tubes: 2x1 perimeter (0.040" wall), 1x1 cross members (0.063" wall)
// Module cutouts: 95.2mm square at 4 corners
// Mechanisms: intake, elevator, arm

annotation { "Feature Type Name" : "2950 Real Frame Robot" }
export const blueprintRealFrame = defineFeature(function(context is Context, id is Id, definition is map)
    precondition {}
    {
        // front_rail (hollow tube)
        fCuboid(context, id + "front_rail_outer", {
            "corner1" : vector(0.00, 0.00, 0.00) * millimeter,
            "corner2" : vector(685.80, 50.80, 25.40) * millimeter
        });
        fCuboid(context, id + "front_rail_inner", {
            "corner1" : vector(1.02, 1.02, 1.02) * millimeter,
            "corner2" : vector(684.78, 49.78, 24.38) * millimeter
        });
        opBoolean(context, id + "front_rail_hollow", {
            "tools" : qCreatedBy(id + "front_rail_inner", EntityType.BODY),
            "targets" : qCreatedBy(id + "front_rail_outer", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // back_rail (hollow tube)
        fCuboid(context, id + "back_rail_outer", {
            "corner1" : vector(0.00, 635.00, 0.00) * millimeter,
            "corner2" : vector(685.80, 685.80, 25.40) * millimeter
        });
        fCuboid(context, id + "back_rail_inner", {
            "corner1" : vector(1.02, 636.02, 1.02) * millimeter,
            "corner2" : vector(684.78, 684.78, 24.38) * millimeter
        });
        opBoolean(context, id + "back_rail_hollow", {
            "tools" : qCreatedBy(id + "back_rail_inner", EntityType.BODY),
            "targets" : qCreatedBy(id + "back_rail_outer", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // left_rail (hollow tube)
        fCuboid(context, id + "left_rail_outer", {
            "corner1" : vector(0.00, 50.80, 0.00) * millimeter,
            "corner2" : vector(50.80, 635.00, 25.40) * millimeter
        });
        fCuboid(context, id + "left_rail_inner", {
            "corner1" : vector(1.02, 51.82, 1.02) * millimeter,
            "corner2" : vector(49.78, 633.98, 24.38) * millimeter
        });
        opBoolean(context, id + "left_rail_hollow", {
            "tools" : qCreatedBy(id + "left_rail_inner", EntityType.BODY),
            "targets" : qCreatedBy(id + "left_rail_outer", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // right_rail (hollow tube)
        fCuboid(context, id + "right_rail_outer", {
            "corner1" : vector(635.00, 50.80, 0.00) * millimeter,
            "corner2" : vector(685.80, 635.00, 25.40) * millimeter
        });
        fCuboid(context, id + "right_rail_inner", {
            "corner1" : vector(636.02, 51.82, 1.02) * millimeter,
            "corner2" : vector(684.78, 633.98, 24.38) * millimeter
        });
        opBoolean(context, id + "right_rail_hollow", {
            "tools" : qCreatedBy(id + "right_rail_inner", EntityType.BODY),
            "targets" : qCreatedBy(id + "right_rail_outer", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_0 (hollow tube)
        fCuboid(context, id + "cross_0_outer", {
            "corner1" : vector(50.80, 609.60, 0.00) * millimeter,
            "corner2" : vector(635.00, 635.00, 25.40) * millimeter
        });
        fCuboid(context, id + "cross_0_inner", {
            "corner1" : vector(52.40, 611.20, 1.60) * millimeter,
            "corner2" : vector(633.40, 633.40, 23.80) * millimeter
        });
        opBoolean(context, id + "cross_0_hollow", {
            "tools" : qCreatedBy(id + "cross_0_inner", EntityType.BODY),
            "targets" : qCreatedBy(id + "cross_0_outer", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_1 (hollow tube)
        fCuboid(context, id + "cross_1_outer", {
            "corner1" : vector(50.80, 50.80, 0.00) * millimeter,
            "corner2" : vector(635.00, 76.20, 25.40) * millimeter
        });
        fCuboid(context, id + "cross_1_inner", {
            "corner1" : vector(52.40, 52.40, 1.60) * millimeter,
            "corner2" : vector(633.40, 74.60, 23.80) * millimeter
        });
        opBoolean(context, id + "cross_1_hollow", {
            "tools" : qCreatedBy(id + "cross_1_inner", EntityType.BODY),
            "targets" : qCreatedBy(id + "cross_1_outer", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_2 (hollow tube)
        fCuboid(context, id + "cross_2_outer", {
            "corner1" : vector(50.80, 330.20, 0.00) * millimeter,
            "corner2" : vector(635.00, 355.60, 25.40) * millimeter
        });
        fCuboid(context, id + "cross_2_inner", {
            "corner1" : vector(52.40, 331.80, 1.60) * millimeter,
            "corner2" : vector(633.40, 354.00, 23.80) * millimeter
        });
        opBoolean(context, id + "cross_2_hollow", {
            "tools" : qCreatedBy(id + "cross_2_inner", EntityType.BODY),
            "targets" : qCreatedBy(id + "cross_2_outer", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // bellypan
        fCuboid(context, id + "bellypan", {
            "corner1" : vector(1.02, 1.02, -3.17) * millimeter,
            "corner2" : vector(684.78, 684.78, 0.00) * millimeter
        });
        // mod_cutout_0 — module cutout
        fCuboid(context, id + "mod_cutout_0_cut", {
            "corner1" : vector(15.88, 15.88, -5.00) * millimeter,
            "corner2" : vector(111.12, 111.12, 30.40) * millimeter
        });
        opBoolean(context, id + "mod_cutout_0_boolean", {
            "tools" : qCreatedBy(id + "mod_cutout_0_cut", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_cutout_1 — module cutout
        fCuboid(context, id + "mod_cutout_1_cut", {
            "corner1" : vector(574.67, 15.88, -5.00) * millimeter,
            "corner2" : vector(669.92, 111.12, 30.40) * millimeter
        });
        opBoolean(context, id + "mod_cutout_1_boolean", {
            "tools" : qCreatedBy(id + "mod_cutout_1_cut", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_cutout_2 — module cutout
        fCuboid(context, id + "mod_cutout_2_cut", {
            "corner1" : vector(15.88, 574.67, -5.00) * millimeter,
            "corner2" : vector(111.12, 669.92, 30.40) * millimeter
        });
        opBoolean(context, id + "mod_cutout_2_boolean", {
            "tools" : qCreatedBy(id + "mod_cutout_2_cut", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_cutout_3 — module cutout
        fCuboid(context, id + "mod_cutout_3_cut", {
            "corner1" : vector(574.67, 574.67, -5.00) * millimeter,
            "corner2" : vector(669.92, 669.92, 30.40) * millimeter
        });
        opBoolean(context, id + "mod_cutout_3_boolean", {
            "tools" : qCreatedBy(id + "mod_cutout_3_cut", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_0_0 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_0_0", {
            "topCenter" : vector(10.88, 10.88, 26.40) * millimeter,
            "bottomCenter" : vector(10.88, 10.88, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_0_0_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_0_0", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_0_1 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_0_1", {
            "topCenter" : vector(116.12, 10.88, 26.40) * millimeter,
            "bottomCenter" : vector(116.12, 10.88, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_0_1_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_0_1", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_0_2 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_0_2", {
            "topCenter" : vector(10.88, 116.12, 26.40) * millimeter,
            "bottomCenter" : vector(10.88, 116.12, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_0_2_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_0_2", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_0_3 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_0_3", {
            "topCenter" : vector(116.12, 116.12, 26.40) * millimeter,
            "bottomCenter" : vector(116.12, 116.12, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_0_3_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_0_3", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_1_0 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_1_0", {
            "topCenter" : vector(569.67, 10.88, 26.40) * millimeter,
            "bottomCenter" : vector(569.67, 10.88, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_1_0_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_1_0", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_1_1 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_1_1", {
            "topCenter" : vector(674.92, 10.88, 26.40) * millimeter,
            "bottomCenter" : vector(674.92, 10.88, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_1_1_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_1_1", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_1_2 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_1_2", {
            "topCenter" : vector(569.67, 116.12, 26.40) * millimeter,
            "bottomCenter" : vector(569.67, 116.12, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_1_2_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_1_2", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_1_3 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_1_3", {
            "topCenter" : vector(674.92, 116.12, 26.40) * millimeter,
            "bottomCenter" : vector(674.92, 116.12, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_1_3_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_1_3", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_2_0 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_2_0", {
            "topCenter" : vector(10.88, 569.67, 26.40) * millimeter,
            "bottomCenter" : vector(10.88, 569.67, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_2_0_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_2_0", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_2_1 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_2_1", {
            "topCenter" : vector(116.12, 569.67, 26.40) * millimeter,
            "bottomCenter" : vector(116.12, 569.67, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_2_1_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_2_1", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_2_2 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_2_2", {
            "topCenter" : vector(10.88, 674.92, 26.40) * millimeter,
            "bottomCenter" : vector(10.88, 674.92, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_2_2_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_2_2", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_2_3 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_2_3", {
            "topCenter" : vector(116.12, 674.92, 26.40) * millimeter,
            "bottomCenter" : vector(116.12, 674.92, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_2_3_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_2_3", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_3_0 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_3_0", {
            "topCenter" : vector(569.67, 569.67, 26.40) * millimeter,
            "bottomCenter" : vector(569.67, 569.67, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_3_0_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_3_0", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_3_1 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_3_1", {
            "topCenter" : vector(674.92, 569.67, 26.40) * millimeter,
            "bottomCenter" : vector(674.92, 569.67, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_3_1_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_3_1", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_3_2 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_3_2", {
            "topCenter" : vector(569.67, 674.92, 26.40) * millimeter,
            "bottomCenter" : vector(569.67, 674.92, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_3_2_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_3_2", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_bolt_3_3 — bolt hole (d=5.0mm)
        fCylinder(context, id + "mod_bolt_3_3", {
            "topCenter" : vector(674.92, 674.92, 26.40) * millimeter,
            "bottomCenter" : vector(674.92, 674.92, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "mod_bolt_3_3_drill", {
            "tools" : qCreatedBy(id + "mod_bolt_3_3", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_0_0 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_0_0", {
            "topCenter" : vector(60.80, 70.80, 26.40) * millimeter,
            "bottomCenter" : vector(60.80, 70.80, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_0_0_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_0_0", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_0_1 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_0_1", {
            "topCenter" : vector(60.80, 50.80, 26.40) * millimeter,
            "bottomCenter" : vector(60.80, 50.80, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_0_1_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_0_1", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_0_2 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_0_2", {
            "topCenter" : vector(70.80, 60.80, 26.40) * millimeter,
            "bottomCenter" : vector(70.80, 60.80, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_0_2_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_0_2", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_0_3 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_0_3", {
            "topCenter" : vector(50.80, 60.80, 26.40) * millimeter,
            "bottomCenter" : vector(50.80, 60.80, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_0_3_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_0_3", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_1_0 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_1_0", {
            "topCenter" : vector(625.00, 70.80, 26.40) * millimeter,
            "bottomCenter" : vector(625.00, 70.80, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_1_0_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_1_0", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_1_1 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_1_1", {
            "topCenter" : vector(625.00, 50.80, 26.40) * millimeter,
            "bottomCenter" : vector(625.00, 50.80, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_1_1_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_1_1", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_1_2 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_1_2", {
            "topCenter" : vector(635.00, 60.80, 26.40) * millimeter,
            "bottomCenter" : vector(635.00, 60.80, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_1_2_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_1_2", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_1_3 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_1_3", {
            "topCenter" : vector(615.00, 60.80, 26.40) * millimeter,
            "bottomCenter" : vector(615.00, 60.80, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_1_3_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_1_3", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_2_0 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_2_0", {
            "topCenter" : vector(60.80, 635.00, 26.40) * millimeter,
            "bottomCenter" : vector(60.80, 635.00, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_2_0_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_2_0", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_2_1 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_2_1", {
            "topCenter" : vector(60.80, 615.00, 26.40) * millimeter,
            "bottomCenter" : vector(60.80, 615.00, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_2_1_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_2_1", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_2_2 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_2_2", {
            "topCenter" : vector(70.80, 625.00, 26.40) * millimeter,
            "bottomCenter" : vector(70.80, 625.00, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_2_2_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_2_2", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_2_3 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_2_3", {
            "topCenter" : vector(50.80, 625.00, 26.40) * millimeter,
            "bottomCenter" : vector(50.80, 625.00, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_2_3_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_2_3", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_3_0 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_3_0", {
            "topCenter" : vector(625.00, 635.00, 26.40) * millimeter,
            "bottomCenter" : vector(625.00, 635.00, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_3_0_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_3_0", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_3_1 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_3_1", {
            "topCenter" : vector(625.00, 615.00, 26.40) * millimeter,
            "bottomCenter" : vector(625.00, 615.00, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_3_1_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_3_1", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_3_2 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_3_2", {
            "topCenter" : vector(635.00, 625.00, 26.40) * millimeter,
            "bottomCenter" : vector(635.00, 625.00, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_3_2_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_3_2", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // gusset_bolt_3_3 — bolt hole (d=5.0mm)
        fCylinder(context, id + "gusset_bolt_3_3", {
            "topCenter" : vector(615.00, 625.00, 26.40) * millimeter,
            "bottomCenter" : vector(615.00, 625.00, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "gusset_bolt_3_3_drill", {
            "tools" : qCreatedBy(id + "gusset_bolt_3_3", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_0_0_a — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_0_0_a", {
            "topCenter" : vector(25.40, 614.30, 26.40) * millimeter,
            "bottomCenter" : vector(25.40, 614.30, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_0_0_a_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_0_0_a", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_0_0_b — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_0_0_b", {
            "topCenter" : vector(25.40, 630.30, 26.40) * millimeter,
            "bottomCenter" : vector(25.40, 630.30, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_0_0_b_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_0_0_b", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_0_1_a — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_0_1_a", {
            "topCenter" : vector(660.40, 614.30, 26.40) * millimeter,
            "bottomCenter" : vector(660.40, 614.30, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_0_1_a_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_0_1_a", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_0_1_b — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_0_1_b", {
            "topCenter" : vector(660.40, 630.30, 26.40) * millimeter,
            "bottomCenter" : vector(660.40, 630.30, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_0_1_b_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_0_1_b", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_1_0_a — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_1_0_a", {
            "topCenter" : vector(25.40, 55.50, 26.40) * millimeter,
            "bottomCenter" : vector(25.40, 55.50, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_1_0_a_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_1_0_a", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_1_0_b — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_1_0_b", {
            "topCenter" : vector(25.40, 71.50, 26.40) * millimeter,
            "bottomCenter" : vector(25.40, 71.50, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_1_0_b_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_1_0_b", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_1_1_a — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_1_1_a", {
            "topCenter" : vector(660.40, 55.50, 26.40) * millimeter,
            "bottomCenter" : vector(660.40, 55.50, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_1_1_a_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_1_1_a", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_1_1_b — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_1_1_b", {
            "topCenter" : vector(660.40, 71.50, 26.40) * millimeter,
            "bottomCenter" : vector(660.40, 71.50, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_1_1_b_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_1_1_b", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_2_0_a — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_2_0_a", {
            "topCenter" : vector(25.40, 334.90, 26.40) * millimeter,
            "bottomCenter" : vector(25.40, 334.90, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_2_0_a_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_2_0_a", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_2_0_b — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_2_0_b", {
            "topCenter" : vector(25.40, 350.90, 26.40) * millimeter,
            "bottomCenter" : vector(25.40, 350.90, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_2_0_b_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_2_0_b", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_2_1_a — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_2_1_a", {
            "topCenter" : vector(660.40, 334.90, 26.40) * millimeter,
            "bottomCenter" : vector(660.40, 334.90, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_2_1_a_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_2_1_a", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // cross_bolt_2_1_b — bolt hole (d=5.0mm)
        fCylinder(context, id + "cross_bolt_2_1_b", {
            "topCenter" : vector(660.40, 350.90, 26.40) * millimeter,
            "bottomCenter" : vector(660.40, 350.90, -1.00) * millimeter,
            "radius" : 2.49 * millimeter
        });
        opBoolean(context, id + "cross_bolt_2_1_b_drill", {
            "tools" : qCreatedBy(id + "cross_bolt_2_1_b", EntityType.BODY),
            "targets" : qAllNonMeshSolidBodies(),
            "operationType" : BooleanOperationType.SUBTRACTION
        });
        // mod_body_0
        fCuboid(context, id + "mod_body_0", {
            "corner1" : vector(25.40, 25.40, 25.40) * millimeter,
            "corner2" : vector(101.60, 101.60, 101.60) * millimeter
        });
        // mod_wheel_0
        fCuboid(context, id + "mod_wheel_0", {
            "corner1" : vector(44.45, 22.23, -85.72) * millimeter,
            "corner2" : vector(82.55, 104.78, -3.17) * millimeter
        });
        // mod_body_1
        fCuboid(context, id + "mod_body_1", {
            "corner1" : vector(584.20, 25.40, 25.40) * millimeter,
            "corner2" : vector(660.40, 101.60, 101.60) * millimeter
        });
        // mod_wheel_1
        fCuboid(context, id + "mod_wheel_1", {
            "corner1" : vector(603.25, 22.23, -85.72) * millimeter,
            "corner2" : vector(641.35, 104.78, -3.17) * millimeter
        });
        // mod_body_2
        fCuboid(context, id + "mod_body_2", {
            "corner1" : vector(25.40, 584.20, 25.40) * millimeter,
            "corner2" : vector(101.60, 660.40, 101.60) * millimeter
        });
        // mod_wheel_2
        fCuboid(context, id + "mod_wheel_2", {
            "corner1" : vector(44.45, 581.02, -85.72) * millimeter,
            "corner2" : vector(82.55, 663.57, -3.17) * millimeter
        });
        // mod_body_3
        fCuboid(context, id + "mod_body_3", {
            "corner1" : vector(584.20, 584.20, 25.40) * millimeter,
            "corner2" : vector(660.40, 660.40, 101.60) * millimeter
        });
        // mod_wheel_3
        fCuboid(context, id + "mod_wheel_3", {
            "corner1" : vector(603.25, 581.02, -85.72) * millimeter,
            "corner2" : vector(641.35, 663.57, -3.17) * millimeter
        });
        // mech_intake
        fCuboid(context, id + "mech_intake", {
            "corner1" : vector(25.40, 254.00, 25.40) * millimeter,
            "corner2" : vector(660.40, 596.90, 317.50) * millimeter
        });
        // mech_elevator
        fCuboid(context, id + "mech_elevator", {
            "corner1" : vector(190.50, 215.90, 25.40) * millimeter,
            "corner2" : vector(495.30, 368.30, 1447.80) * millimeter
        });
        // mech_arm
        fCuboid(context, id + "mech_arm", {
            "corner1" : vector(266.70, 190.50, 76.20) * millimeter,
            "corner2" : vector(419.10, 393.70, 279.40) * millimeter
        });
        // elec_battery
        fCuboid(context, id + "elec_battery", {
            "corner1" : vector(252.40, 254.10, 0.00) * millimeter,
            "corner2" : vector(433.40, 330.10, 167.00) * millimeter
        });
        // elec_pdh
        fCuboid(context, id + "elec_pdh", {
            "corner1" : vector(266.70, 120.65, 0.00) * millimeter,
            "corner2" : vector(419.10, 222.25, 38.10) * millimeter
        });
        // elec_roborio
        fCuboid(context, id + "elec_roborio", {
            "corner1" : vector(254.00, 412.75, 0.00) * millimeter,
            "corner2" : vector(431.80, 501.65, 38.10) * millimeter
        });
        // elec_radio
        fCuboid(context, id + "elec_radio", {
            "corner1" : vector(275.40, 456.85, 0.00) * millimeter,
            "corner2" : vector(410.40, 571.85, 30.00) * millimeter
        });
        // elec_main_breaker
        fCuboid(context, id + "elec_main_breaker", {
            "corner1" : vector(485.85, 314.40, 0.00) * millimeter,
            "corner2" : vector(542.85, 371.40, 38.00) * millimeter
        });
    });
