FeatureScript 2931;
import(path : "onshape/std/common.fs", version : "2931.0");

// THE ENGINE — Full Robot Blueprint
// Generated by The Blueprint B.7 — CAD Builder
// Frame: 27.0" x 27.0"
// Mechanisms: intake, conveyor, flywheel, climber

annotation { "Feature Type Name" : "2950 Blueprint Robot" }
export const blueprintRobot = defineFeature(function(context is Context, id is Id, definition is map)
    precondition {}
    {
        // front_rail
        fCuboid(context, id + "front_rail", {
            "corner1" : vector(0.0, 0.0, 0.0) * millimeter,
            "corner2" : vector(685.8, 50.8, 25.4) * millimeter
        });
        // back_rail
        fCuboid(context, id + "back_rail", {
            "corner1" : vector(0.0, 635.0, 0.0) * millimeter,
            "corner2" : vector(685.8, 685.8, 25.4) * millimeter
        });
        // left_rail
        fCuboid(context, id + "left_rail", {
            "corner1" : vector(0.0, 50.8, 0.0) * millimeter,
            "corner2" : vector(50.8, 635.0, 25.4) * millimeter
        });
        // right_rail
        fCuboid(context, id + "right_rail", {
            "corner1" : vector(635.0, 50.8, 0.0) * millimeter,
            "corner2" : vector(685.8, 635.0, 25.4) * millimeter
        });
        // cross_0
        fCuboid(context, id + "cross_0", {
            "corner1" : vector(50.8, 609.6, 0.0) * millimeter,
            "corner2" : vector(635.0, 635.0, 25.4) * millimeter
        });
        // cross_1
        fCuboid(context, id + "cross_1", {
            "corner1" : vector(50.8, 50.8, 0.0) * millimeter,
            "corner2" : vector(635.0, 76.2, 25.4) * millimeter
        });
        // cross_2
        fCuboid(context, id + "cross_2", {
            "corner1" : vector(50.8, 330.2, 0.0) * millimeter,
            "corner2" : vector(635.0, 355.6, 25.4) * millimeter
        });
        // bellypan
        fCuboid(context, id + "bellypan", {
            "corner1" : vector(1.0, 1.0, -3.2) * millimeter,
            "corner2" : vector(684.8, 684.8, 0.0) * millimeter
        });
        // mod_body_0
        fCuboid(context, id + "mod_body_0", {
            "corner1" : vector(25.4, 25.4, 25.4) * millimeter,
            "corner2" : vector(101.6, 101.6, 101.6) * millimeter
        });
        // mod_wheel_0
        fCuboid(context, id + "mod_wheel_0", {
            "corner1" : vector(44.5, 22.2, -85.7) * millimeter,
            "corner2" : vector(82.5, 104.8, -3.2) * millimeter
        });
        // mod_body_1
        fCuboid(context, id + "mod_body_1", {
            "corner1" : vector(584.2, 25.4, 25.4) * millimeter,
            "corner2" : vector(660.4, 101.6, 101.6) * millimeter
        });
        // mod_wheel_1
        fCuboid(context, id + "mod_wheel_1", {
            "corner1" : vector(603.2, 22.2, -85.7) * millimeter,
            "corner2" : vector(641.3, 104.8, -3.2) * millimeter
        });
        // mod_body_2
        fCuboid(context, id + "mod_body_2", {
            "corner1" : vector(25.4, 584.2, 25.4) * millimeter,
            "corner2" : vector(101.6, 660.4, 101.6) * millimeter
        });
        // mod_wheel_2
        fCuboid(context, id + "mod_wheel_2", {
            "corner1" : vector(44.5, 581.0, -85.7) * millimeter,
            "corner2" : vector(82.5, 663.6, -3.2) * millimeter
        });
        // mod_body_3
        fCuboid(context, id + "mod_body_3", {
            "corner1" : vector(584.2, 584.2, 25.4) * millimeter,
            "corner2" : vector(660.4, 660.4, 101.6) * millimeter
        });
        // mod_wheel_3
        fCuboid(context, id + "mod_wheel_3", {
            "corner1" : vector(603.2, 581.0, -85.7) * millimeter,
            "corner2" : vector(641.3, 663.6, -3.2) * millimeter
        });
        // mech_intake
        fCuboid(context, id + "mech_intake", {
            "corner1" : vector(25.4, 139.7, 25.4) * millimeter,
            "corner2" : vector(660.4, 596.9, 431.8) * millimeter
        });
        // mech_conveyor
        fCuboid(context, id + "mech_conveyor", {
            "corner1" : vector(190.5, 38.1, 25.4) * millimeter,
            "corner2" : vector(495.3, 647.7, 431.8) * millimeter
        });
        // mech_flywheel
        fCuboid(context, id + "mech_flywheel", {
            "corner1" : vector(215.9, 69.8, 431.8) * millimeter,
            "corner2" : vector(469.9, 273.0, 635.0) * millimeter
        });
        // mech_climber
        fCuboid(context, id + "mech_climber", {
            "corner1" : vector(241.3, 50.8, 25.4) * millimeter,
            "corner2" : vector(444.5, 152.4, 787.4) * millimeter
        });
        // elec_battery
        fCuboid(context, id + "elec_battery", {
            "corner1" : vector(252.4, 254.1, 0.0) * millimeter,
            "corner2" : vector(433.4, 330.1, 167.0) * millimeter
        });
        // elec_pdh
        fCuboid(context, id + "elec_pdh", {
            "corner1" : vector(266.7, 120.6, 0.0) * millimeter,
            "corner2" : vector(419.1, 222.2, 38.1) * millimeter
        });
        // elec_roborio
        fCuboid(context, id + "elec_roborio", {
            "corner1" : vector(254.0, 412.8, 0.0) * millimeter,
            "corner2" : vector(431.8, 501.6, 38.1) * millimeter
        });
        // elec_radio
        fCuboid(context, id + "elec_radio", {
            "corner1" : vector(275.4, 456.8, 0.0) * millimeter,
            "corner2" : vector(410.4, 571.8, 30.0) * millimeter
        });
        // elec_main_breaker
        fCuboid(context, id + "elec_main_breaker", {
            "corner1" : vector(485.8, 314.4, 0.0) * millimeter,
            "corner2" : vector(542.8, 371.4, 38.0) * millimeter
        });
    });
